fixing errors in the code of the 1st workflow

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,23 +1,24 @@
 name: 01 - Building Blocks
 on: push
-trigger: workflow_dispatch
+
 
 jobs:
   
   echo-hello:
     runs-on: ubuntu-latest
     steps:  
-      name: Say hello
-      run: echo 'Hello world'
+      - name: Say hello
+        run: echo 'Hello world'
   
   echo-goodbye:
+    runs-on: ubuntu-latest
     steps:
-      name: Failed step   
-      run: |
-        echo 'I'
-        echo 'will'
-        echo 'fail'
-        echo 1
+      - name: Failed step   
+        run: |
+          echo 'I'
+          echo 'will'
+          echo 'fail'
+          exit 1
 
-      name: Say goodbye
-      run: echo 'Goodbye!'     
+      - name: Say goodbye
+        run: echo 'Goodbye!'     
